### ISSUE TITLE
Cookie help

### ISSUE THREAD

**Issue by ghost** [clouderrific/vitalsource-downloader#2]
Can you explain in a bit more detail what to paste in here: const globalCookieVal = ``. 

I see long strings for cookies _jigsaw_session, jig_isbns, and reese84 from jigsaw.vitalsource.com in my web browser. I'm just not sure which string or what order or format to paste them in between the ``. Any help appreciated.

**Comment by clouderrific** [comment]
Easiest way to grab the "correct" cookie is by supplying all the cookies :-)

1. Open the browser of your choosing (Chrome).
2. Navigate to the book that you are trying to download.
3. Open the browser developer tools and access the network sessions.
4. Refresh the page to capture all of the network sessions.
5. Select a sessions that originates from jigsaw.vitalsource.com and has cookies such as `https://jigsaw.vitalsource.com/secure-token`
6. Inspect the Request Headers for a key `cookie` that contains `_jigsaw_session` in the value string.
7. Copy the entire `Set-Cookie` value string and paste it into the script provided.

I hope that helps!

**Comment by ghost** [comment]
Thank you!!!!!!!! Now I can print my books and not have to stare at the computer all night. Much appreciated.
